#!/usr/bin/env python3
"""Refresh the generated contributed-projects section in README.md."""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request
import urllib.parse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
REPOS = ROOT / ".github" / "contributed-repos.json"
START = "<!-- contributed-projects:start -->"
END = "<!-- contributed-projects:end -->"
AUTHOR = "justinpbarnett"


def github_request(url: str) -> dict | list:
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "justinpbarnett-profile-readme",
        },
    )
    if token:
        request.add_header("Authorization", f"Bearer {token}")

    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        details = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API failed for {url}: {error.code} {details}") from error


def load_repo_names() -> list[str]:
    entries = json.loads(REPOS.read_text(encoding="utf-8"))
    names = []
    for entry in entries:
        repo = entry["repo"] if isinstance(entry, dict) else entry
        names.append(repo)
    return names


def format_stars(count: int) -> str:
    return f"{count:,}"


def repo_metadata(repo: str) -> dict:
    return github_request(f"https://api.github.com/repos/{repo}")


def merged_prs_by_author(repo: str) -> list[dict]:
    query = urllib.parse.quote(f"repo:{repo} is:pr is:merged author:{AUTHOR}")
    data = github_request(f"https://api.github.com/search/issues?q={query}&per_page=25")
    return data["items"]


def has_approval_review(repo: str, pull_number: int) -> bool:
    reviews = github_request(f"https://api.github.com/repos/{repo}/pulls/{pull_number}/reviews")
    return any(review.get("state") == "APPROVED" for review in reviews)


def qualifying_pull_request(repo: str) -> dict | None:
    for pull in merged_prs_by_author(repo):
        if has_approval_review(repo, pull["number"]):
            return {
                "number": pull["number"],
                "url": pull["html_url"],
            }
    return None


def build_section() -> str:
    repos = []
    for repo in load_repo_names():
        pull = qualifying_pull_request(repo)
        if not pull:
            print(f"Skipping {repo}: no approved merged PR by {AUTHOR}", file=sys.stderr)
            continue

        data = repo_metadata(repo)
        repos.append(
            {
                "name": data["full_name"],
                "url": data["html_url"],
                "stars": int(data["stargazers_count"]),
                "pull": pull,
            }
        )

    repos.sort(key=lambda item: (-item["stars"], item["name"].lower()))

    lines = [
        START,
        "<!-- This section is generated by scripts/update_contributed_projects.py. -->",
        "| Project | Stars |",
        "| --- | ---: |",
    ]
    for repo in repos:
        lines.append(
            f"| [{repo['name']}]({repo['url']}) | {format_stars(repo['stars'])} |"
        )
    lines.append(END)
    return "\n".join(lines)


def update_readme() -> bool:
    readme = README.read_text(encoding="utf-8")
    pattern = re.compile(f"{re.escape(START)}.*?{re.escape(END)}", re.DOTALL)
    updated, count = pattern.subn(build_section(), readme)
    if count != 1:
        raise RuntimeError(f"Expected exactly one generated section in {README}, found {count}")
    if updated == readme:
        return False
    README.write_text(updated, encoding="utf-8")
    return True


def main() -> int:
    changed = update_readme()
    print("README.md updated" if changed else "README.md already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
